// import './globals.css'
// import NavBar from "@/components/NavBar";
// import Footer from "@/components/Footer";
// import { Lora } from 'next/font/google';

// const lora = Lora({
//     subsets: ['latin'],
// });
// export const metadata = {
//   title: "IC2SDT 2025",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head />
//       <body className="bg-primary05" style={{
//           fontFamily: lora.style.fontFamily
//       }}>
//       <NavBar />
//       {children}
//       <Footer />
//       </body>
//     </html>
//   )
// }
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Raleway } from "next/font/google";

const raleway = Raleway({
    subsets: ["latin"],
    weight: ["300", "400", "700"], // Ensures proper font weights
});

export const metadata = {
  title: "IC2SDT 2025",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head />
      <body className={`${raleway.className} bg-primary05`}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
